"""Re-exports from tomd.lib.shared for backward compatibility."""

from tomd.lib.shared import (  # noqa: F401
    ALLOWED_LINK_SCHEMES,
    DATE_RE,
    DEFAULT_FENCE_LANG,
    DOC_NUM_PATTERN,
    DOC_NUM_RE,
    EMAIL_RE,
    FORMAT_CHARS,
    FRONT_MATTER_ORDER,
    SECTION_NUM_PATTERN,
    SECTION_NUM_PREFIX_RE,
    ascii_escape,
    dedup_paragraphs,
    deobfuscate_email,
    enrich_reply_to_names,
    format_front_matter,
    normalize_date,
    parse_author_lines,
    sanitize_metadata,
    strip_format_chars,
    strip_leading_h1,
    strip_freeform_metadata_lines,
    strip_redundant_body_meta,
)
